### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by anthonyaxenov**
I translated documentation from scratch from English to Russian

### CODE REVIEW

**Comment by SimplyCorey** [comment]
Thank you 🎂

**Comment by SimplyCorey** [comment]
@anthonyaxenov, thanks for the PR request.  I am unable to read Russian, so before I merge this I would like to know what was changed.  Was the old Russian transaction not well done?

**Comment by anthonyaxenov** [comment]
Well, old translation was made by machine - as always it is not so good as could be. I made it more correct lexically and syntactically. For example, the name of the package should not be translated. I changed many synonyms to fit the context. Also, some phrases were confused and incomprehensible.

I always ready to improve translation according to notices (if any).

**Comment by SimplyCorey** [comment]
I really appreciate it.  I will merge this into the v2 branch tomorrow.  I am working on getting v3 out for this package.  Would you be interested in translating the new docs when they are ready?

Again thank you 🙏

**Comment by anthonyaxenov** [comment]
Yes, I think I can

**Pull request merged**
