### PR TITLE
Update QrCode.php, compatible with the IDE

### PR DESCRIPTION
**Pull request by maxsky**
Make the PhpStorem/IDEA can be find method like generate and set size, color, etc.

### CODE REVIEW

**Comment by SimplyCorey** [comment]
Thanks for the PR request.  With the v3 rewrite, these changes no longer apply.

Feel free to make a new PR with v3 and I will merge it. :)

**Comment by maxsky** [comment]
A year has passed... ;)

**Comment by SimplyCorey** [comment]
Yes 😞 Time goes by quickly, but I appreciate the PR regardless 🙃

**Comment by maxsky** [comment]
Thx

**Pull request closed without merging**
